// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordResetMailer is an autogenerated mock type for the PasswordResetMailer type
type PasswordResetMailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: email, resetTok
func (_m *PasswordResetMailer) Send(email string, resetTok string) error {
	ret := _m.Called(email, resetTok)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, resetTok)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
