// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "github.com/calebmcelroy/tradelead-auth/core/entity"
import mock "github.com/stretchr/testify/mock"

// TokenRepo is an autogenerated mock type for the TokenRepo type
type TokenRepo struct {
	mock.Mock
}

// Delete provides a mock function with given fields: token
func (_m *TokenRepo) Delete(token string) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: token
func (_m *TokenRepo) Get(token string) (entity.Token, error) {
	ret := _m.Called(token)

	var r0 entity.Token
	if rf, ok := ret.Get(0).(func(string) entity.Token); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(entity.Token)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *TokenRepo) Insert(_a0 entity.Token) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Token) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
